navigation:
    dist_to_marker: 0.45
    pos_thres: 0.2      # not used yet
    yaw_thres: 0.1      # not used yet
    vel_thres: 0.1      # not used yet
    vel_yaw_thres: 0.05 # not used yet
    2d_height: 0.5

#tested process noise : [0.001, 0.001, 0.001, 0.001, 0.001, 0.001]
localization:
    process_noise: [0.01, 0.01, 0.01, 0.01, 0.01, 0.01]  # used in v5
    initial_cov: [100000, 100000, 100000, 100000, 100000, 100000] # used in v5
    maha_dist_thres: 7
    cov_norm_thres: 0.03
    measurement_config: [true, true, true,   # translation x,y,z
                         false, false, true] # rotation roll,pitch,yaw
    initial_map_to_odom: [1, 1, 0, 0, 0, 1.57] # [x,y,z,roll,pitch,yaw]

perception:
    img_size: [[480, 640], [446, 332]]  #H, W
    focal: [221.88078347, 220.72391163]   #Fx, Fy
    aruco_cov: [0.5, 0.5, 0.5, 0.3, 0.3, 0.3] # used in marker_pose
    sign_cov: [0.1, 0.1, 0.1, -1, -1, -1] # not used in marker_pose


path_planning:
    rho: 0.2
    inflation: 0.2
