navigation:
    dist_to_marker: 0.5
    pos_thres: 0.2      # not used yet
    yaw_thres: 0.1      # not used yet
    vel_thres: 0.1      # not used yet
    vel_yaw_thres: 0.05 # not used yet

localization:
    process_noise: [0.005, 0.005, 0.005, 0.005, 0.005, 0.005]  # used in v5
    initial_cov: [100000, 100000, 100000, 100000, 100000, 100000] # used in v5
    maha_dist_thres: 3
    cov_norm_thres: 0.02
    measurement_config: [true, true, false,   # translation x,y,z
                         false, false, true] # rotation roll,pitch,yaw
    initial_map_to_odom: [1, 1, 0, 0, 0, 1.57] # [x,y,z,roll,pitch,yaw]
    aruco_cov: [0.1, 0.1, 0.1, 0.1, 0.1, 0.1] # not used right now
    sign_cov: [0.1, 0.1, 0.1, -1, -1, -1] # not used right now
perception:
    todo: "TODO"

path_planning:
    rho: 0.15
    inflation: 0.1
