#!/usr/bin/env python

import cv2
#from cv_bridge import CvBridge, CvBridgeError
#import roslib
#import rospy


cfgFile = file('yolov3-tiny.cfg','r')
darknetModel = file('yolov3-tiny.weights','r')
darkModel = cv2.dnn.readNetFromDarknet(cfgFile, darknetModel)
