#!/usr/bin/env python

import rospy
import tf2_ros
import tf2_geometry_msgs
from geometry_msgs.msg import Twist, PoseStamped

class InpCmdPos:
    def __init__(self):
        self.pub_cmd = rospy.Publisher("cf1/move_to", PoseStamped, queue_size=2)
        self.cf1_pos_top = rospy.Subscriber('/cf1/pose', PoseStamped, self.cf1_pose_callback)        
        self.cf1_pose = None

        #self.debug_pub = rospy.Publisher("cf1/pose", PoseStamped, queue_size=2)

    def cf1_pose_callback(self, msg):
        self.cf1_pose = msg

    def spin(self):
        rate = rospy.Rate(20)  # Hz
        while not rospy.is_shutdown():
            pos = raw_input('x, y, relative (0/1) = ')
            
            try:
                x,y,rel = [float(p.strip()) for p in pos.split(",")]
                x = -x
            except:
                rospy.loginfo("Something went wrong...")
            else:
                rospy.loginfo("Relative: {}".format(rel))
                rospy.loginfo("Cf1 pose: {}".format(self.cf1_pose))
                if rel and self.cf1_pose:
                    rospy.loginfo("Creating relative goal...")
                    x += self.cf1_pose.pose.position.x
                    y += self.cf1_pose.pose.position.y
                goal = PoseStamped()
                goal.header.stamp = rospy.Time.now()
                goal.header.frame_id = "cf1/odom"
                goal.pose.position.x, goal.pose.position.y = x, y
                goal.pose.position.z = 0.5
                self.pub_cmd.publish(goal)
                rospy.loginfo("Publishing goal ({}, {})...".format(goal.pose.position.x, goal.pose.position.y))
            rate.sleep()


if __name__ == '__main__':
    rospy.init_node('inp_cmd_pos')
    InpCmdPos().spin()
